### ISSUE TITLE
Bug Report: "FormatException: Input string was not in a correct format."

### ISSUE THREAD

**Issue by Shigure-kai-2** [CrazyGamesCom/unity-optimizations-package#8] opened 2023-03-02 09:55 UTC
Hello, when I used WebGL Optimizer to analyze the editor report, it gave feedback "FormatException: Input string was not in a correct format.", in script BuildLogs.cs. And the error lines are _var size = float.Parse(splitLine[0], CultureInfo.InvariantCulture.NumberFormat);_ and _var sizePercentage = float.Parse(splitLine[2].Replace("%", ""), CultureInfo.InvariantCulture.NumberFormat);_  I changed the Parse into TryParse and it worked, but I don't know whether it will make some differences in the analysis results. Could you plz check for this issue?

**Comment by florin-ciornei** [comment] 2023-04-03 07:30
Hi @Shigure-kai-2 , thanks for reporting this. We are currently working on fixing it.

**Comment by florin-ciornei** [comment] 2023-04-03 07:59
@Shigure-kai-2 could you share more details with us:

- The Unity editor version you are using
- From the Editor.log file (Tools > WebGL optimizer > Build logs, and click the button Open Editor.log), the build report, including the first few lines of assets. Example below (no need to share the entire file, since it may contain personal information).

-------------------------------------------------------------------------------
Build Report
Uncompressed usage by category (Percentages based on user generated assets only):
Textures               4.2 mb	 15.8% 
Meshes                 466.8 kb	 1.7% 
Animations             0.0 kb	 0.0% 
Sounds                 7.0 mb	 26.5% 
Shaders                141.7 kb	 0.5% 
Other Assets           425.8 kb	 1.6% 
Levels                 135.2 kb	 0.5% 
Scripts                726.1 kb	 2.7% 
Included DLLs          13.3 mb	 50.6% 
File headers           15.5 kb	 0.1% 
Total User Assets      26.3 mb	 100.0% 
Complete build size    42.1 mb
Used Assets and files from the Resources folder, sorted by uncompressed size:
 3.5 mb	 8.3% Assets/Resources/Nested folder/Music 1.mp3
 3.5 mb	 8.3% Assets/Resources/Music.mp3
 2.7 mb	 6.3% Assets/Resources/water-large.jpg

My first impression was that perhaps the Editor.log file uses different decimal separators (9.3 vs 9,3), however in this case there shouldn't be an exception, just an incorrect number parsing.

**Comment by florin-ciornei** [comment] 2023-04-11 07:12
I'll close this for now due to not being able to reproduce it. @Shigure-kai-2  (or if anyone else stumbles upon this), if you still encounter this problem, please create a new issue with the info I requested here https://github.com/CrazyGamesCom/unity-optimizations-package/issues/8#issuecomment-1493854992

**Closed by florin-ciornei** 2023-04-11 07:12 UTC
